### ISSUE TITLE
.NET Core nuget package

### ISSUE THREAD

**Issue by Nothing4You** [poma/ProxySocket#1]
Hello,

please add support for .NET Core, currently trying to add this package to a project fails like this:
```
Restoring packages for ...
Package ProxySocket 1.1.2 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package ProxySocket 1.1.2 supports: net40 (.NETFramework,Version=v4.0)
One or more packages are incompatible with .NETCoreApp,Version=v1.1.
Package restore failed. Rolling back package changes for '...'.
```

**Comment by poma** [comment]
I don't know how to build packages for .NET core, maybe if someone makes a pull request

**Comment by honfika** [comment]
Hi @poma,

Could you please merge @sh2ezo's PR? I'd like to also use this project from .NET Core.

**Comment by poma** [comment]
done
