### ISSUE TITLE
.NET Core Project Target Framework

### ISSUE THREAD

**Issue by miou-gh** [poma/ProxySocket#4]
`warning NU1701: Package 'ProxySocket 1.1.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.`

It'd be good if there was a target project for .NET core specifically to avoid these warnings.

**Comment by miou-gh** [comment]
On top of this, I seem to be getting the following exception whenever I try to use it regardless.
`
System.IO.FileNotFoundException: 'Could not load file or assembly 'ProxySocket, Version=1.1.2.0, Culture=neutral, PublicKeyToken=966874d7118d1436'. The system cannot find the file specified.'
`

**Comment by poma** [comment]
fixed
