### ISSUE TITLE
Socks5 Connection Without Username/Pass?

### ISSUE THREAD

**Issue by nordgee** [poma/ProxySocket#5]
Hello, It appears that there is no way for me to connect to a Socks5 proxy server that does not use a use username/password.

The Socks5 proxy server I am trying to connect to does not need a password to connect. So how do I connect to Socks5 server without a username and password using your ProxySocket class? Whenever I try to connect without setting "ProxyUser" and "ProxyPass" it says "Username/password combination not accepted."

Any help would be appreciated, thanks for your time.

**Comment by poma** [comment]
You should be able to connect using null user and pass. If server does not accept, it's very likely that it requires some non null user and password, check its auth settings
